### ISSUE TITLE
Newest update compatibility

### ISSUE THREAD

**Issue by KodeMannn** [CW-Jesse/valheim-betternetworking#16]
Is this mod still working with the newest update that just released?

**Comment by CustozZ** [comment]
Hello, yes I've wondered aswell what exactly changed in the last update, could anything go wrong? From what I understand they mostly worked on the freeze that happens when the save occures so it should be totally ok with betternetworking?

I'm asking because I host a server for some friends and without CWJesseBetternetworking it's almost unplayable sometimes

**Comment by CW-Jesse** [comment]
It should work as of 2.3.1 thanks to @jpw1991! Please re-open this ticket if it doesn't work for you.

**Comment by CustozZ** [comment]
Hello, from alot of people: thank you for allowing us to play together without major desyncs etc, have a good week
